import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "@/components/ui/toaster";
const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "TeamVLR | Build your dream team",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-[#0B0B0B] antialiased `}>
        <Analytics />
        <Toaster />
        <div className="w-full relative flex">
          <Navbar />
        </div>
        <div className=" flex items-center justify-center">{children}</div>
        <div className="flex justify-center items-center p-4">
          <h1 className="text-white/50">
            Developed by{" "}
            <Link className="font-bold" href={"https://grkn.dev"}>
              @grkndev
            </Link>
          </h1>
        </div>
      </body>
    </html>
  );
}
