import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "@/components/ui/toaster";
const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-[#0B0B0B] antialiased `}>
        <Analytics />
        <Toaster />
        <div className="w-full relative flex">
          <Navbar />
        </div>
        <div className=" flex items-center justify-center">{children}</div>
        <div className="flex justify-center items-center p-4">
          <h1 className="text-white/50">
            Developed by{" "}
            <Link className="font-bold" href={"https://grkn.dev"}>
              @grkndev
            </Link>
          </h1>
        </div>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  metadataBase: new URL("https://teamvlr.net"),
  robots: { index: true, follow: true },
  title: "TeamVLR | Build your VALORANT team.",
  keywords: [
    "TeamVLR",
    "teamvlr",
    "team vlr",
    "team.vlr",
    "teamvlr.net",
    "vlr.gg",
    "vlr.gg sen",
    "vlr.gg bracket",
    "vlr.gg pickems",
    "vlr.gg champions 2024",
    "vlr.gg nrg",
    "vlr.gg prx",
    "vlr.gg fnatic",
    "vlr.gg g2",
    "vlr.gg api",
    "vlr.gg drx",
    "vlr.gg americas",
    "vlr.gg aspas",
    "vlr.gg americas stage 2",
    "vlr.gg alternative",
    "vlr.gg app",
    "vlr.gg apeks",
    "vlr.gg apac",
    "vlr.gg autumn",
    "vlr.gg alecks interview",
    "aspas vlr gg",
    "alfajer vlr gg",
    "apeks vlr gg",
    "ardiis vlr.gg",
    "afreecatv vlr.gg",
    "ardis vlr gg",
    "acend vlr gg",
    "vlr gg americas",
    "vlr gg americas 2024",
    "vlr.gg blg",
    "vlr.gg boostio",
    "vlr.gg bleed",
    "vlr.gg benjyfishy",
    "vlr.gg bbl",
    "vlr.gg boom",
    "vlr.gg bracket 2024",
    "vlr how long to beat",
    "bleed vlr.gg",
    "bbl vlr gg",
    "benjyfishy vlr.gg",
    "boostio vlr.gg",
    "blg vlr.gg",
    "benkai vlr.gg",
    "bbl queens vlr gg",
    "boom vlr gg",
    "vlr gg bbk",
    "vlr.gg champions 2023",
    "vlr.gg c9",
    "vlr.gg champions",
    "vlr.gg champs",
    "vlr.gg c0m",
    "vlr.gg champions 2022",
    "vlr.gg champion points",
    "vlr.gg challengers",
    "vlr.gg champions seoul",
    "c9 vlr.gg",
    "curry vlr.gg",
    "chronicle vlr.gg",
    "cned vlr gg",
    "convergence vlr gg",
    "champions vlr.gg",
    "champions 2022 vlr.gg",
    "vlr gg champions 2024",
    "vlr.gg champions 2021",
    "vlr.gg down",
    "vlr.gg demon1",
    "vlr.gg dfm",
    "vlr.gg dsg",
    "vlr.gg discord",
    "vlr.gg dapr",
    "vlr.gg dgzin",
    "vlr gg disguised",
    "vlr gg dsg gc",
    "drx vlr gg",
    "dsg vlr.gg",
    "demon1 vlr.gg",
    "dfm vlr.gg",
    "derke vlr gg",
    "drg vlr gg",
    "d3ffo vlr.gg",
    "da vlr gg",
    "is vlr.gg down",
    "vlr.gg eg",
    "vlr.gg edg",
    "vlr.gg emea stage 2",
    "vlr.gg events",
    "vlr.gg emea",
    "vlr.gg eg vs prx",
    "vlr.gg edg vs th",
    "vlr gg emea kickoff",
    "vlr.gg eg vs loud",
    "vlr gg emea lcq",
    "eg vlr gg",
    "edg vlr gg",
    "ethan vlr.gg",
    "eternal fire vlr gg",
    "emea vlr gg",
    "elite vlr gg",
    "ef vlr gg",
    "vlr gg prx vs eg",
    "vlr gg prx vs edg",
    "vlr.gg furia",
    "vlr.gg fns",
    "vlr.gg fpx",
    "vlr.gg fut",
    "vlr.gg for league of legends",
    "vlr.gg forsaken",
    "vlr.gg for lol",
    "vlr.gg full sense",
    "vlr.fg",
    "fnatic vlr gg",
    "fns vlr.gg",
    "fpx vlr.gg",
    "florescent vlr.gg",
    "furia vlr gg",
    "fut vlr gg",
    "fullsense vlr.gg",
    "forsaken vlr.gg",
    "fokus vlr.gg",
    "fennel vlr.gg",
    "vlr.gg geng",
    "vlr.gg ge",
    "vlr.gg geng vs sen",
    "vlr.gg giantx",
    "vlr.gg gamechangers",
    "vlr.gg gambit",
    "vlr.gg geng vs th",
    "vlr gg g2 gozen",
    "vlr gg gs",
    "g2 vlr gg",
    "geng vlr.gg",
    "ge vlr.gg",
    "giantx vlr.gg",
    "governor vlr.gg",
    "game changers vlr gg",
    "giants vlr gg",
    "g2 gozen vlr gg",
    "gambit vlr gg",
    "galatasaray vlr gg",
    "vlr.gg heretics",
    "vlr.gg hiro",
    "vlr.gg haodong",
    "vlr gg howl",
    "vlr.hg",
    "vlr.hh",
    "heretics vlr gg",
    "hiro vlr gg",
    "howl vlr gg",
    "vlr.gg",
    "vlr.gh",
    "vlr.gg icy",
    "vlr.gg iam",
    "vlr gg lock in",
    "vlr.gg sentinels invitational",
    "vlr gg vct indonesia",
    "vlr gg iw",
    "vlr istanbul",
    "iw vlr gg",
    "vlr.gg jinggg",
    "vlr.gg jawgemo",
    "vlr .gg japan",
    "johnqt vlr.gg",
    "vlr johnqt",
    "vlr jumpydoll",
    "jinggg vlr.gg",
    "v lr.gg",
    "vlr.gv",
    "vlr.g",
    "vlr.gg kru",
    "vlr.gg karon",
    "vlr.gg kc",
    "vlr.gg koi",
    "vlr gg kpi",
    "vlr.gg kickoff americas",
    "vlr.gg pacific kickoff",
    "keiko vlr gg",
    "keenc vlr.gg",
    "kru vlr gg",
    "koi vlr gg",
    "kc vlr gg",
    "karon vlr.gg",
    "vlr.gg americas kickoff",
    "vlr.gg lev",
    "vlr.gg loud",
    "vlr.gg lakia",
    "vlr.gg leaf",
    "vlr.gg leo",
    "vlr.gg liquid",
    "vlr.gg logo",
    "vlr.gg less",
    "vlr.gg lol",
    "vlr.gg lev vs g2",
    "lev vlr gg",
    "loud vlr gg",
    "leo vlr.gg",
    "less vlr.gg",
    "leaf vlr.gg",
    "liquid vlr gg",
    "lucks vlr.gg",
    "lock in vlr gg",
    "vlr.gg sen vs lev",
    "vlr.gg madrid",
    "vlr.gg mibr",
    "vlr.gg m80",
    "vlr.gg masters shanghai",
    "vlr.gg mxs",
    "vlr.gg masters tokyo",
    "vlr.gg miniboo",
    "vlr.gg m8",
    "vlr.gg matches",
    "vlr.gg mith",
    "m80 vlr.gg",
    "mibr vlr.gg",
    "mith vlr gg",
    "masters madrid vlr.gg",
    "monyet vlr gg",
    "mindfreak vlr gg",
    "mxs vlr gg",
    "masters shanghai vlr.gg",
    "m8 vlr gg",
    "masters tokyo vlr.gg",
    "vlr.gg net",
    "vlr.gg navi",
    "vlr.gg na challengers",
    "vlr.gg na",
    "vlr.gg nrg vs kru",
    "vlr gg nats",
    "vlr.gg noot noot",
    "vlr.gg sen vs nrg",
    "nivera vlr gg",
    "nrg vlr.gg",
    "navi vlr gg",
    "nats vlr gg",
    "vlr gg na",
    "nvlr-shop. com",
    "vlr.gg oxy",
    "vlr.gg owner",
    "vlr.gg oxygen",
    "vlr.gg optic",
    "vlr op gg",
    "vlr gg kick off",
    "vlr oxg",
    "vlr.gg sentinels",
    "oxy vlr.gg",
    "oxygen esports vlr gg",
    "optic vlr.gg",
    "who owns vlr.gg",
    "vlr.gg primmie",
    "vlr.gg pacific",
    "vlr.gg",
  ],
  description:
    "TeamVLR | Build your VALORANT team. We are not affiliated with Riot Games.",
  openGraph: {
    images: ["/og-image1.jpg"],
    type: "website",
    siteName: "TeamVLR",
    title: "TeamVLR | Build your VALORANT team.",
    description:
      "TeamVLR | Build your VALORANT team. We are not affiliated with Riot Games.",
    locale: "en_US",
    url: "https://teamvlr.net",
  },
  twitter: {
    card: "summary_large_image",
    title: "TeamVLR | Build your VALORANT team.",
    description:
      "TeamVLR | Build your VALORANT team. We are not affiliated with Riot Games.",
    images: ["/og-image1.jpg"],
    site: "https://teamvlr.net",
    creator: "@grkndev",
  },
};
